// BlueprintGeneratedClass BPSessionFunctionLibrary.BPSessionFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UBPSessionFunctionLibrary_C : UBlueprintFunctionLibrary {

	void CalculateProspectState(struct FFProspectServerInfo FProspectServerInfo, struct AIcarusPlayerController* Target, struct UObject* __WorldContext, enum class E_ProspectState ProspectState); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.CalculateProspectState // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a38c80
	void HaveJoinedProspect(struct FString UserID, struct TArray<struct FAssociatedMemberInfo> Members, struct UObject* __WorldContext, bool AssignedToProspect, enum class EProspectLocation Status); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.HaveJoinedProspect // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a38c80
	void WrapMemberData(struct TArray<struct FAssociatedMemberInfo> AssociatedMembers, struct UObject* __WorldContext, struct FString MemberData); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.WrapMemberData // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1a38c80
	void HasSettled(struct AIcarusPlayerController* Target, struct FFProspectServerInfo FProspectServerInfo, struct UObject* __WorldContext, bool Settled); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.HasSettled // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a38c80
	void MakeSessionSearchFilters(struct UObject* __WorldContext, struct TArray<struct FSessionsSearchSetting> Filters); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.MakeSessionSearchFilters // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1a38c80
	void GetSessionProperties(struct TArray<struct FSessionPropertyKeyPair> Session Extra Settings, struct UObject* __WorldContext, struct FString ProspectUID, struct FString ProspectDTKey, struct FString FractionMissionDTKey, struct FString LobbyName, struct FString OwnerID, int32_t OwnerCharacter, int32_t ExpireTime, enum class EProspectState ProspectState, int32_t Cost, int32_t Reward); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.GetSessionProperties // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a38c80
	void CreateProspectServerInfoFromSession(struct FBlueprintSessionResult Session, struct UObject* __WorldContext, struct FFProspectServerInfo ServerProspect); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.CreateProspectServerInfoFromSession // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a38c80
	void ProspectInfoIsValid(struct FFProspectServerInfo Server Prospect Info, bool RequiresSession, struct UObject* __WorldContext, bool Valid); // Function BPSessionFunctionLibrary.BPSessionFunctionLibrary_C.ProspectInfoIsValid // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a38c80
};

